const Types = {
  RESET_STATE: "RESET_STATE",
  SET_YOUR_SCORE: "SET_YOUR_SCORE",
  SET_LEVEL: "SET_LEVEL",
  SET_PLAYER_TURN: "SET_PLAYER_TURN",
  SET_CLICKED_LINE: "SET_CLICKED_LINE",
  SET_BORDER_COUNT: "SET_BORDER_COUNT",
  SET_GAME_BOARD: "SET_GAME_BOARD"
}

export default Types;
