const Types = {
  RESET_STATE: "RESET_STATE",
  SET_YOUR_SCORE: "SET_YOUR_SCORE",
  SET_LEVEL: "SET_LEVEL",
  SET_PLAYER_TURN: "SET_PLAYER_TURN",
  SET_CLICKED_LINE: "SET_CLICKED_LINE",
  SET_BORDER_COUNT: "SET_BORDER_COUNT",
  SET_GAME_BOARD: "SET_GAME_BOARD",
  SET_CONNECTED_BOXES: "SET_CONNECTED_BOXES",
  SET_INITIAL_FOOT_INDEXES: "SET_INITIAL_FOOT_INDEXES",
  SET_FOOT_INDEXES: "SET_FOOT_INDEXES",
  SET_BORDERS: "SET_BORDERS",
  SET_WHO_CLICKED_THE_LINE: "SET_WHO_CLICKED_THE_LINE",
  SET_BOARD: "SET_BOARD",
  SET_WHO_SCORE: "SET_WHO_SCORE"
}

export default Types;
